[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "index.html,app.html,migrazione.html"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
